### ISSUE TITLE
Clarification on instructions.

### ISSUE THREAD

**Issue by mikathebun** [FaultyFunctions/GShade-Block#4]
Hi there! I just need some clarification here.

If I am currently using V4.1 for GSHADE, do I need to just replace the .dll file and thats it?

Do I still need to do the hex editor stuff?

**Comment by AudieMurphy135** [comment]
You don't have to do the hex editor stuff.

Contrary to what the instructions say, placing the file in the GShade installation folder doesn't work (at least, not for me). It needs to be renamed to dxgi.dll and placed within your FF14 installation's /game/ folder (move/delete the old dxgi.dll). I'm on 4.1 and it works perfectly when I do this.

**Comment by FaultyFunctions** [comment]
@mikathebun Let me know if @AudieMurphy135 suggestion works for you and thanks for the reply Audie.

Alternatively you can try using the [GShade Patcher](https://notnite.com/gshade-patcher.html) that [@NotNite](https://twitter.com/NotNite) has created since you are running v4.1. I would try this first since this is a more robust and automated patch than my workaround.

Let me know if you get it figured out!

**Comment by mikathebun** [comment]
> You don't have to do the hex editor stuff.
> 
> Contrary to what the instructions say, placing the file in the GShade installation folder doesn't work (at least, not for me). It needs to be renamed to dxgi.dll and placed within your FF14 installation's /game/ folder (move/delete the old dxgi.dll). I'm on 4.1 and it works perfectly when I do this.

So I am replacing the .dll in the game folder, not the gshade folder? Correct me if I am wrong, just don't want to bork it up.

**Comment by mikathebun** [comment]
> @mikathebun Let me know if @AudieMurphy135 suggestion works for you and thanks for the reply Audie.
> 
> Alternatively you can try using the [GShade Patcher](https://notnite.com/gshade-patcher.html) that [@NotNite](https://twitter.com/NotNite) has created since you are running v4.1. I would try this first since this is a more robust and automated patch than my workaround.
> 
> Let me know if you get it figured out!

Hello! I just ended up using the patcher provided by NotNite! Easy peasy!

Will eventually go to reshade, but for the time being this will do.

**Comment by FaultyFunctions** [comment]
Glad that worked out for you! For anyone else stumbling upon this, it should be replacing the `GShade64.dll` in the GShade folder otherwise renaming the `GShade64.dll` you download to `dxgi.dll` and replacing the one in the game folder will work.

But using the patcher linked is the best option.

Closing this issue, thanks!
